services:
  api:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Docker-specific overrides
      WAIT_FOR_DB: "false"      # Don't wait for Docker services
      WAIT_FOR_REDIS: "false"   # Using external services
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/liveness"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped