"""Initial schema

Revision ID: 6c6fcf9133ce
Revises: 
Create Date: 2025-06-06 01:10:42.295936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c6fcf9133ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('caller_name', sa.String(length=200), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('audio_file_paths', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('transcript_segments', sa.JSON(), nullable=False),
    sa.Column('llm_responses', sa.JSON(), nullable=False),
    sa.Column('error_messages', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('context_data', sa.JSON(), nullable=False),
    sa.Column('automation_triggered', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('satisfaction_score', sa.Float(), nullable=True),
    sa.Column('resolution_achieved', sa.Boolean(), nullable=True),
    sa.Column('call_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calls_phone_number'), 'calls', ['phone_number'], unique=False)
    op.create_index(op.f('ix_calls_session_id'), 'calls', ['session_id'], unique=False)
    op.create_index(op.f('ix_calls_tenant_id'), 'calls', ['tenant_id'], unique=False)
    op.create_table('tenants_persistence',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('max_calls_per_month', sa.Integer(), nullable=False),
    sa.Column('features_stt_enabled', sa.Boolean(), nullable=False),
    sa.Column('features_tts_enabled', sa.Boolean(), nullable=False),
    sa.Column('features_llm_enabled', sa.Boolean(), nullable=False),
    sa.Column('features_automation_enabled', sa.Boolean(), nullable=False),
    sa.Column('features_knowledge_base_enabled', sa.Boolean(), nullable=False),
    sa.Column('subscription_plan', sa.String(length=50), nullable=False),
    sa.Column('subscription_expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users_persistence',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_persistence_email'), 'users_persistence', ['email'], unique=True)
    op.create_index(op.f('ix_users_persistence_tenant_id'), 'users_persistence', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_users_persistence_username'), 'users_persistence', ['username'], unique=False)
    op.create_table('call_sessions',
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('current_turn', sa.String(length=20), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.Column('state_changed_at', sa.DateTime(), nullable=False),
    sa.Column('current_audio_stream_id', sa.String(length=100), nullable=True),
    sa.Column('is_recording', sa.Boolean(), nullable=False),
    sa.Column('is_playing', sa.Boolean(), nullable=False),
    sa.Column('conversation_history', sa.JSON(), nullable=False),
    sa.Column('current_prompt', sa.Text(), nullable=True),
    sa.Column('last_user_input', sa.Text(), nullable=True),
    sa.Column('last_ai_response', sa.Text(), nullable=True),
    sa.Column('pending_stt_requests', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('pending_llm_requests', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('pending_tts_requests', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('max_silence_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('max_session_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('session_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_sessions_session_id'), 'call_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_call_sessions_tenant_id'), 'call_sessions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_sessions_tenant_id'), table_name='call_sessions')
    op.drop_index(op.f('ix_call_sessions_session_id'), table_name='call_sessions')
    op.drop_table('call_sessions')
    op.drop_index(op.f('ix_users_persistence_username'), table_name='users_persistence')
    op.drop_index(op.f('ix_users_persistence_tenant_id'), table_name='users_persistence')
    op.drop_index(op.f('ix_users_persistence_email'), table_name='users_persistence')
    op.drop_table('users_persistence')
    op.drop_table('tenants_persistence')
    op.drop_index(op.f('ix_calls_tenant_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_session_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_phone_number'), table_name='calls')
    op.drop_table('calls')
    # ### end Alembic commands ###
