"""Add user preferences table

Revision ID: 87e22e272944
Revises: 02bef89540f7
Create Date: 2025-06-06 01:18:29.577847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87e22e272944'
down_revision = '02bef89540f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.Column('language_ui', sa.String(length=10), nullable=False),
    sa.Column('sidebar_collapsed', sa.Boolean(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('push_notifications', sa.Boolean(), nullable=False),
    sa.Column('sms_notifications', sa.Boolean(), nullable=False),
    sa.Column('auto_answer_calls', sa.Boolean(), nullable=False),
    sa.Column('preferred_tts_voice', sa.String(length=50), nullable=False),
    sa.Column('preferred_stt_model', sa.String(length=50), nullable=False),
    sa.Column('max_call_duration', sa.Integer(), nullable=False),
    sa.Column('default_dashboard_view', sa.String(length=50), nullable=False),
    sa.Column('items_per_page', sa.Integer(), nullable=False),
    sa.Column('custom_settings', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_persistence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_tenant_id'), 'user_preferences', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preferences_tenant_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
